name: shivalikcityapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  modal_bottom_sheet: ^3.0.0
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  percent_indicator: ^4.2.3
  flutter_tts: ^4.0.2
  translator: ^1.0.0
  #  rake: ^1.0.1
  pie_chart: ^5.4.0
  connectivity: ^3.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/default_profile_pic.jpg
  uses-material-design: true

